package io.github.rikoappdev.composepdf

import org.apache.pdfbox.Loader
import org.apache.pdfbox.text.PDFTextStripper
import java.awt.Color as AwtColor
import java.awt.image.BufferedImage
import java.io.ByteArrayOutputStream
import java.io.File
import javax.imageio.ImageIO
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Regression for splittable bordered cards: a day is a bordered `box` with a 3-column summary, a long
 * works list, and an atomic photo grid, repeated across records. A day taller than a page must break
 * the bordered card across pages (border redrawn per fragment) without clipping content or overrunning
 * the footer — the behaviour that previously required hand-rolled pagination in the consuming app.
 */
class WorkingDayReproTest {

    private fun regular() = File("src/jvmTest/resources/font/NotoSans-Regular.ttf").readBytes()
    private fun bold() = File("src/jvmTest/resources/font/NotoSans-Bold.ttf").readBytes()

    private fun jpeg(): ByteArray {
        val img = BufferedImage(640, 480, BufferedImage.TYPE_INT_RGB)
        val g = img.createGraphics(); g.color = AwtColor(0x80, 0x80, 0x80); g.fillRect(0, 0, 640, 480); g.dispose()
        val out = ByteArrayOutputStream(); ImageIO.write(img, "jpg", out); return out.toByteArray()
    }

    @Test
    fun borderedDayCardSplitsAcrossPagesWithoutClipping() {
        val ink = Color(0xFF212529); val muted = Color(0xFF6C757D); val dark = Color(0xFF343A40)
        val photo = jpeg()

        val pdf = pdfDocument(PageConfig(margin = 36.dp)) {
            header {
                row(gap = 12.dp) {
                    cell(3f) { text("ACME Inc.", TextStyle(fontSize = 10.sp, fontWeight = FontWeight.Bold, color = ink)) }
                    cell(3f) { text("Investor: Example Ltd.", TextStyle(fontSize = 10.sp, fontWeight = FontWeight.Bold, color = ink, align = TextAlign.End)) }
                }
                divider(muted)
            }
            footer { text("Generated by compose-pdf", TextStyle(fontSize = 8.sp, color = muted)) }
            text("Daily records", TextStyle(fontSize = 9.sp, fontWeight = FontWeight.Bold, color = ink))
            spacer(8.dp)

            repeat(2) { d ->
                box(border = 1.dp, borderColor = muted) {
                    box(padding = 8.dp, background = dark) {
                        row {
                            cell(3f) { text("Day ${d + 1}", TextStyle(fontSize = 11.sp, fontWeight = FontWeight.Bold, color = PdfColor.White)) }
                            cell(2f) { text("Hours: 8.0", TextStyle(fontSize = 9.sp, color = PdfColor.White, align = TextAlign.End)) }
                        }
                    }
                    box(padding = 10.dp) {
                        row(gap = 10.dp) {
                            cell(1f) { text("Workers", TextStyle(fontSize = 11.sp, fontWeight = FontWeight.Bold, color = ink)); spacer(3.dp); repeat(3) { text("Worker $it — 8h", TextStyle(fontSize = 8.sp, color = ink)) } }
                            cell(1f) { text("Machines", TextStyle(fontSize = 11.sp, fontWeight = FontWeight.Bold, color = ink)); spacer(3.dp); repeat(2) { text("Machine $it — 4h", TextStyle(fontSize = 8.sp, color = ink)) } }
                            cell(1f) { text("Materials", TextStyle(fontSize = 11.sp, fontWeight = FontWeight.Bold, color = ink)); spacer(3.dp); repeat(2) { text("Material $it — 10", TextStyle(fontSize = 8.sp, color = ink)) } }
                        }
                        spacer(8.dp)
                        text("Work done", TextStyle(fontSize = 11.sp, fontWeight = FontWeight.Bold, color = ink))
                        repeat(50) { text("• Task $it for day ${d + 1} — a long description that wraps across the full content width so the day card grows beyond one page and must break.", TextStyle(fontSize = 8.sp, color = ink)) }
                        spacer(8.dp)
                        text("Photos", TextStyle(fontSize = 11.sp, fontWeight = FontWeight.Bold, color = ink))
                        spacer(4.dp)
                        photoGrid(listOf(photo, photo, photo, photo, photo), perRow = 3, cellHeight = 70.dp)
                        spacer(10.dp)
                        text("Signature: ______________________", TextStyle(fontSize = 8.sp, color = ink))
                    }
                }
                spacer(10.dp)
            }
        }.render(regular(), bold())

        File("build").mkdirs()
        File("build/working-day-repro.pdf").writeBytes(pdf)

        // Valid structure.
        assertTrue(pdf.copyOf(8).decodeToString().startsWith("%PDF-"), "missing PDF header")
        assertTrue(pdf.copyOfRange(pdf.size - 32, pdf.size).decodeToString().contains("%%EOF"), "missing %%EOF")

        Loader.loadPDF(pdf).use { doc ->
            // Two long days must span several pages (proves the card splits, not clips).
            assertTrue(doc.numberOfPages >= 3, "expected the cards to split across pages, got ${doc.numberOfPages}")
            val text = PDFTextStripper().getText(doc)
            assertTrue("Day 1" in text && "Day 2" in text, "both day cards must render")
            // First and last works of both days survive (nothing clipped at page edges).
            assertTrue("Task 0 for day 1" in text && "Task 49 for day 1" in text, "day 1 works clipped")
            assertTrue("Task 0 for day 2" in text && "Task 49 for day 2" in text, "day 2 works clipped")
        }
    }
}
